### PR TITLE
Pull Request to Master Branch

### PR DESCRIPTION
**Pull request by erichilarysmithsr**
Pull request to Master Branch for updating index.html

### CODE REVIEW

**Comment by Rudxain** [comment]
wtf is this? This is totally off-topic

**Comment by erichilarysmithsr** [comment]
What do you mean?

**Comment by Rudxain** [comment]
- This is not a website, it's a library (which does have a website, but for docs)
- This isn't NodeJS-specific
- This is not "Basic Math Skills", and this lib isn't made only for learning purposes (it's a lib that adds fraction objects, to do rational arithmetic)

**Comment by erichilarysmithsr** [comment]
Look I know how to use the math library, it's reusable code like it or
not.  Support it for educational purposes

**Comment by Rudxain** [comment]
> I know how to use the math library

I didn't meant to say that you don't, I was just describing the lib. I'm sorry if I sounded harsh

> it's reusable code

That's true, you're right

> Support it for educational purposes

What do you mean? Is that "I support it" or "you should support it"? Either way, that's nice! I agree

I meant that even though it can be used as educational resource, that's not the main purpose

**Comment by erichilarysmithsr** [comment]
Got it.

**Pull request closed without merging**
