### PR TITLE
Changed from throwing strings to throwing custom subtypes of Error.

### PR DESCRIPTION
**Pull request by EposnowHQ**
Throwing strings for errors means you do not get stack traces for errors impossible. I know throwing strings was probably done for size reasons, but personally I consider it worth the extra size.

### CODE REVIEW

**Comment by infusion** [comment]
Thanks for the pull request! You're absolutely right about stack traces and the reason for this abstract error handling is the file size. But having this feature would be worth the additional bytes. However, I have to look into your PR more precisely, as fraction.js is dependency of a few projects and don't want to break tests there.

**Comment by cameron-martin** [comment]
Have you had time to have a look at this?

**Comment by kevinbarabash** [comment]
I opened https://github.com/infusion/Fraction.js/issues/11 without checking the open PRs.  I was going to submit a PR that just wrapped each of the strings with `new Error()`.  This is a much better solution, I hope it gets merged.

**Comment by infusion** [comment]
Sorry for my late response on this, I finally merged it.

**Pull request merged**
